server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    ##jdbc:mysql://127.0.0.1:3306/test
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

#springmvc
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.dexian.pro1.pojo

#showsql
logging:
  level:
    com:
      dexian : debug


